### ISSUE TITLE
Allow bare type variables in the RHS only if they appear bare in the pattern

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#132]
In his proof Richard showed that this definition should not be accepted as injective:

``` haskell
type family F a = r | r -> a
type instance F [a] = a
```

Reason: `F [F Int] ~ F Int` (from equation for `F`) and from injectivity we have `[F Int] ~ Int`.

Proposed solution: allow bare type variables in the RHS only if they appear bare in the LHS pattern.

**Comment by goldfirere** [comment]
It's worse than just this. Not only do they have to appear bare on the LHS, the bare variable must be the only variable on the LHS.

Consider this:

```
type family F a b = r | r -> a b
type instance F a Int = a
```

Now, we can see that `F (F Bool Bool) Int ~ F Bool Bool` and thus, by injectivity, `Int ~ Bool`. So, the only injective type family with a bare variable on the right is `Id a = a`.

**Comment by jstolarek** [comment]
Urgh.

> Now, we can see that F (F Bool Bool) Int ~ F Bool Bool and thus, by injectivity, Int ~ Bool.

Equally interestingly we can also see `F Bool Bool ~ Bool`. We just created a new type family equation :-)

**Comment by jstolarek** [comment]
Almost done - kind polymorphism trips my current implementation:

``` haskell
type family F (a :: k) = (r :: k) | r -> a where
  F a =a
```

Internally `k` is also an argument to `F` and so it seems `F` has two patterns rather than one.

**Comment by jstolarek** [comment]
Already implemented.
