### ISSUE TITLE
Validate failures after a rebase

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#144]
After a rebase on 16th of July there are several unexpected validation failures:

```
   polykinds                 T6068 [bad stderr] (ghci)
   polykinds                 T7128 [exit code non-0] (normal)
   polykinds                 T7230 [stderr mismatch] (normal)
   polykinds                 T7973 [exit code non-0] (normal)
   typecheck/should_fail     tcfail220 [exit code 0] (normal)
```

The first four are either panics or bogus errors around `AnyK`. The last one should fail compilation but it succeeds.

**Comment by jstolarek** [comment]
The first four tests now pass correctly. The only remaining problem is `tcfail220`, which should fail but doesn't.

**Comment by simonpj** [comment]
tcfail220 is, if I recall, something to do with .hisg files.   I think we can safely ignore it for now; all of this hsig stuff is being up-heaved by Edward, and no one else uses it.

So we are good!

Simon
